config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("categories/", include("categories.urls", namespace="genres")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import resolve_home, resolve_search

app_name="core"

urlpatterns = [
  path("", resolve_home, name="home"),
  path("search", resolve_search, name="search")
]

users/urls.py
from django.urls import path
from users.views import logout_view, LoginView, SignUpView, UserProfileView, UpdateProfileView, UpdatePasswordView

app_name = "people"

urlpatterns = [
    path("logout", logout_view, name="logout"),
    path("login", LoginView.as_view(), name="login"),
    path("signup", SignUpView.as_view(), name="signup"),
    path("<int:pk>", UserProfileView.as_view(), name="profile"),
    path("update-profile/", UpdateProfileView.as_view(), name="update"),
    path("update-password/", UpdatePasswordView.as_view(), name="password"),
]

templates/partials/footer.html
<footer class="ml-10 mt-5 mb-5">
  &copy; Nomad Media
</footer>

templates/partials/header.html
  <div class="w-full h-full flex justify-center items-center text-lg">  <img class="h-10 bg-cover bg-center rounded-2xl mb-2 mt-5" src="https://nomadcoders.co/m.svg" />Nomad Library</div>
  <header class="flex justify-around bg-red-400 text-white py-4 bg-gradient-to-r from-yellow-400 via-red-500 to-pink-500 ">
    <a href="{% url 'core:home' %}">Home</a>
    <a href="{% url 'core:search' %}">Search</a>
    {% if user.is_authenticated %}
      <a href="{% url 'users:logout' %}">Log Out</a>
      <a href="{% url 'users:profile' user.pk %}">My Profile</a>
    {% else %}
      <a href="{% url 'users:login' %}">Log In</a>
      <a href="{% url 'users:signup' %}">Sign Up</a>
    {% endif %}
  </header>